workflows:
  ionic-capacitor-ios-app:
    name: App
    environment:
      vars:
        XCODE_WORKSPACE: "App.xcworkspace"
        XCODE_SCHEME: "App"
      node: latest
    scripts:
      - npm install
      - ionic build
      - npx cap sync
      - npx cap sync ios
      - |
          # build iOS
          cd ios/App
          pod install
          xcodebuild build -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
