workflows:
  ionic-capacitor-ios-app:
    name: Ionic App
    environment:
      vars:
        XCODE_WORKSPACE: "ios/App/MyApp.xcworkspace"
        XCODE_SCHEME: "MyApp"
      node: latest
    scripts:
      - npm install
      - npx cap sync
      - |
          # build iOS
          cd platforms/ios
          pod install
          xcodebuild build -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
