version: '3.4'

services:
  web:
    image: ${DOCKER_REGISTRY-}web
    container_name: web
    build:
      context: .
      dockerfile: src/Web/Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - myapp

  db:
    image: "postgres:15"
    container_name: "db"
    platform: "linux/arm64"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "wanderlust-nest"
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - myapp

volumes:
  db-data:
    
networks:
  myapp:
    driver: bridge