version: '3.4'

services:
  web:
    image: ${DOCKER_REGISTRY-}web
    container_name: web
    build:
      context: .
      dockerfile: src/Web/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
#     depends_on:
#       - db

#   db:
#     image: "mcr.microsoft.com/mssql/server"
#     environment:
#       SA_PASSWORD: "Password123!"
#       ACCEPT_EULA: "Y"
#     ports:
#       - "1433:1433"
#     volumes:
#       - db-data:/var/opt/mssql

# volumes:
#   db-data: