version: '3.4'

services:
  web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8000
      - ASPNETCORE_HTTPS_PORTS=8001
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "5000"
      - "5001"
    volumes:
      - ./secrets:/home/app/.microsoft/usersecrets:ro
      - ./https:/home/app/.aspnet/https:ro