import { AppCountries } from '../types/country.types';

export const appCountries: Record<string, AppCountries> = {
  AED: {
    key: 'AED',
    countryName: 'United Arab Emirates',
    currencyName: 'Dirham',
    symbol: 'د.إ',
  },
  AFN: {
    key: 'AFN',
    countryName: 'Afghanistan',
    currencyName: 'Afghani',
    symbol: '؋',
  },
  ALL: { key: 'ALL', countryName: 'Albania', currencyName: 'Lek', symbol: 'L' },
  AMD: {
    key: 'AMD',
    countryName: 'Armenia',
    currencyName: 'Dram',
    symbol: '֏',
  },
  ANG: {
    key: 'ANG',
    countryName: 'Netherlands Antilles',
    currencyName: 'Guilder',
    symbol: 'ƒ',
  },
  AOA: {
    key: 'AOA',
    countryName: 'Angola',
    currencyName: 'Kwanza',
    symbol: 'Kz',
  },
  ARS: {
    key: 'ARS',
    countryName: 'Argentina',
    currencyName: 'Peso',
    symbol: '$',
  },
  AUD: {
    key: 'AUD',
    countryName: 'Australia',
    currencyName: 'Dollar',
    symbol: 'A$',
  },
  AWG: {
    key: 'AWG',
    countryName: 'Aruba',
    currencyName: 'Florin',
    symbol: 'ƒ',
  },
  AZN: {
    key: 'AZN',
    countryName: 'Azerbaijan',
    currencyName: 'Manat',
    symbol: '₼',
  },
  BAM: {
    key: 'BAM',
    countryName: 'Bosnia and Herzegovina',
    currencyName: 'Convertible Mark',
    symbol: 'KM',
  },
  BBD: {
    key: 'BBD',
    countryName: 'Barbados',
    currencyName: 'Dollar',
    symbol: 'Bds$',
  },
  BDT: {
    key: 'BDT',
    countryName: 'Bangladesh',
    currencyName: 'Taka',
    symbol: '৳',
  },
  BGN: {
    key: 'BGN',
    countryName: 'Bulgaria',
    currencyName: 'Lev',
    symbol: 'лв',
  },
  BHD: {
    key: 'BHD',
    countryName: 'Bahrain',
    currencyName: 'Dinar',
    symbol: '.د.ب',
  },
  BIF: {
    key: 'BIF',
    countryName: 'Burundi',
    currencyName: 'Franc',
    symbol: 'FBu',
  },
  BMD: {
    key: 'BMD',
    countryName: 'Bermuda',
    currencyName: 'Dollar',
    symbol: '$',
  },
  BND: {
    key: 'BND',
    countryName: 'Brunei',
    currencyName: 'Dollar',
    symbol: 'B$',
  },
  BOB: {
    key: 'BOB',
    countryName: 'Bolivia',
    currencyName: 'Boliviano',
    symbol: 'Bs.',
  },
  BRL: {
    key: 'BRL',
    countryName: 'Brazil',
    currencyName: 'Real',
    symbol: 'R$',
  },
  BSD: {
    key: 'BSD',
    countryName: 'Bahamas',
    currencyName: 'Dollar',
    symbol: 'B$',
  },
  BTN: {
    key: 'BTN',
    countryName: 'Bhutan',
    currencyName: 'Ngultrum',
    symbol: 'Nu.',
  },
  BWP: {
    key: 'BWP',
    countryName: 'Botswana',
    currencyName: 'Pula',
    symbol: 'P',
  },
  BYN: {
    key: 'BYN',
    countryName: 'Belarus',
    currencyName: 'Ruble',
    symbol: 'Br',
  },
  CAD: {
    key: 'CAD',
    countryName: 'Canada',
    currencyName: 'Dollar',
    symbol: 'C$',
  },
  CHF: {
    key: 'CHF',
    countryName: 'Switzerland',
    currencyName: 'Franc',
    symbol: 'CHF',
  },
  CLP: { key: 'CLP', countryName: 'Chile', currencyName: 'Peso', symbol: '$' },
  CNY: {
    key: 'CNY',
    countryName: 'China',
    currencyName: 'Yuan Renminbi',
    symbol: '¥',
  },
  COP: {
    key: 'COP',
    countryName: 'Colombia',
    currencyName: 'Peso',
    symbol: '$',
  },
  CRC: {
    key: 'CRC',
    countryName: 'Costa Rica',
    currencyName: 'Colon',
    symbol: '₡',
  },
  CZK: {
    key: 'CZK',
    countryName: 'Czech Republic',
    currencyName: 'Koruna',
    symbol: 'Kč',
  },
  DKK: {
    key: 'DKK',
    countryName: 'Denmark',
    currencyName: 'Krone',
    symbol: 'kr',
  },
  DOP: {
    key: 'DOP',
    countryName: 'Dominican Republic',
    currencyName: 'Peso',
    symbol: 'RD$',
  },
  DZD: {
    key: 'DZD',
    countryName: 'Algeria',
    currencyName: 'Dinar',
    symbol: 'دج',
  },
  EGP: { key: 'EGP', countryName: 'Egypt', currencyName: 'Pound', symbol: '£' },
  EUR: {
    key: 'EUR',
    countryName: 'Eurozone',
    currencyName: 'Euro',
    symbol: '€',
  },
  FJD: {
    key: 'FJD',
    countryName: 'Fiji',
    currencyName: 'Dollar',
    symbol: 'FJ$',
  },
  GBP: {
    key: 'GBP',
    countryName: 'United Kingdom',
    currencyName: 'Pound Sterling',
    symbol: '£',
  },
  GEL: {
    key: 'GEL',
    countryName: 'Georgia',
    currencyName: 'Lari',
    symbol: '₾',
  },
  GHS: { key: 'GHS', countryName: 'Ghana', currencyName: 'Cedi', symbol: '₵' },
  GMD: {
    key: 'GMD',
    countryName: 'Gambia',
    currencyName: 'Dalasi',
    symbol: 'D',
  },
  GTQ: {
    key: 'GTQ',
    countryName: 'Guatemala',
    currencyName: 'Quetzal',
    symbol: 'Q',
  },
  GYD: {
    key: 'GYD',
    countryName: 'Guyana',
    currencyName: 'Dollar',
    symbol: 'G$',
  },
  HKD: {
    key: 'HKD',
    countryName: 'Hong Kong',
    currencyName: 'Dollar',
    symbol: 'HK$',
  },
  HRK: {
    key: 'HRK',
    countryName: 'Croatia',
    currencyName: 'Kuna',
    symbol: 'kn',
  },
  HUF: {
    key: 'HUF',
    countryName: 'Hungary',
    currencyName: 'Forint',
    symbol: 'Ft',
  },
  IDR: {
    key: 'IDR',
    countryName: 'Indonesia',
    currencyName: 'Rupiah',
    symbol: 'Rp',
  },
  ILS: {
    key: 'ILS',
    countryName: 'Israel',
    currencyName: 'Shekel',
    symbol: '₪',
  },
  INR: { key: 'INR', countryName: 'India', currencyName: 'Rupee', symbol: '₹' },
  ISK: {
    key: 'ISK',
    countryName: 'Iceland',
    currencyName: 'Krona',
    symbol: 'kr',
  },
  JMD: {
    key: 'JMD',
    countryName: 'Jamaica',
    currencyName: 'Dollar',
    symbol: 'J$',
  },
  JOD: {
    key: 'JOD',
    countryName: 'Jordan',
    currencyName: 'Dinar',
    symbol: 'د.ا',
  },
  JPY: { key: 'JPY', countryName: 'Japan', currencyName: 'Yen', symbol: '¥' },
  KES: {
    key: 'KES',
    countryName: 'Kenya',
    currencyName: 'Shilling',
    symbol: 'KSh',
  },
  KGS: {
    key: 'KGS',
    countryName: 'Kyrgyzstan',
    currencyName: 'Som',
    symbol: 'с',
  },
  KHR: {
    key: 'KHR',
    countryName: 'Cambodia',
    currencyName: 'Riel',
    symbol: '៛',
  },
  KMF: {
    key: 'KMF',
    countryName: 'Comoros',
    currencyName: 'Franc',
    symbol: 'CF',
  },
};
