# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  web:
    build:
      context: "/Users/manuelraso/Documents/repo/wanderlust-nest/backend"
      dockerfile: "src/Web/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/CleanArchitectureBaseTemplate.Web.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "web:dev"
    ports: []
    volumes:
    - "/Users/manuelraso/Documents/repo/wanderlust-nest/backend/src/Web:/app:rw"
    - "/Users/manuelraso/Documents/repo/wanderlust-nest/backend:/src:rw"
    - "/Users/manuelraso/.nuget/packages:/home/app/.nuget/packages"
    working_dir: "/app"
